services:
  meme-ingester:
    container_name: meme-ingester
    image: ghcr.io/iankulin/meme-ingester:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data